import pytest
import httpx
import uuid
import time

BASE_URL = "http://localhost:80/api"

@pytest.mark.asyncio
async def test_ai_marketing_brain_flow():
    sender_phone = f"555{uuid.uuid4().int % 1000000:06d}"
    message_id = f"msg_{uuid.uuid4().hex}"
    
    # We send structured JSON as the mock Gemini response
    mock_gemini_json = """
    {
      "intent": "purchase",
      "sentiment": "positive",
      "replyStyle": "Sales",
      "entities": {
        "city": "Cairo",
        "budget": 2000000.0,
        "interests": ["Real Estate"],
        "timeline": "Next month"
      },
      "replyContent": "Hello! I see you want to buy a property in Cairo. We have great options matching your 2M EGP budget. How can we proceed?",
      "confidence": 0.95
    }
    """

    async with httpx.AsyncClient(timeout=20.0) as client:
        # 1. Create Project
        proj_resp = await client.post(f"{BASE_URL}/projects", json={"name": "MarketingTestProj"})
        assert proj_resp.status_code == 201
        proj_id = proj_resp.json()["id"]

        # 2. Update Settings to ENABLE AI auto-reply and inject our mock response as API Key (since mock key returns itself)
        headers = {"X-Project-Id": proj_id}
        settings_resp = await client.put(f"{BASE_URL}/projects/{proj_id}/settings", headers=headers, json={
            "aiAutoReplyEnabled": True,
            "timezone": "UTC",
            "geminiApiKey": f"mock_json_{mock_gemini_json}" # We will configure our C# mock to recognize mock_json_ and return the rest!
        })
        assert settings_resp.status_code == 200

        # 3. Setup mock WhatsApp session and connect it
        start_resp = await client.post(f"{BASE_URL}/whatsapp/session/start", json={
            "projectId": proj_id
        })
        assert start_resp.status_code == 200

        await client.post(f"{BASE_URL}/whatsapp/session/mock", json={
            "projectId": proj_id,
            "status": "Connected",
            "phoneNumber": "1234567890"
        })

        # 4. Clear any existing mock sent messages
        await client.post(f"{BASE_URL}/whatsapp/mock/clear")

        # 5. Ingest incoming message via webhook
        webhook_resp = await client.post(
            f"{BASE_URL}/webhooks/whatsapp/message",
            json={
                "projectId": proj_id,
                "messageId": message_id,
                "sender": sender_phone,
                "content": "Hi, I am looking to buy a house in Cairo with 2M budget.",
                "messageType": "Text",
                "timestamp": int(time.time())
            }
        )
        assert webhook_resp.status_code == 200

        # 6. Wait for message aggregation and AI processing (total 14 seconds)
        print("Waiting for message aggregation and AI reply generation...")
        await pytest.importorskip("asyncio").sleep(14.0)

        # 7. Check if the gateway received the AI reply
        sent_resp = await client.get(f"{BASE_URL}/whatsapp/mock/sent")
        assert sent_resp.status_code == 200
        sent_messages = sent_resp.json()

        # Find the message sent to our sender_phone
        reply_message = next((m for m in sent_messages if m["to"] == sender_phone), None)
        assert reply_message is not None, "AI Reply was not sent to WhatsApp Gateway"
        
        # Verify the reply content matches what was generated by the mock JSON
        assert "I see you want to buy a property in Cairo" in reply_message["message"]

        # 8. Check if the customer CRM profile got updated (US3)
        # First, find the customer by phone or list project customers
        customers_resp = await client.get(f"{BASE_URL}/projects/{proj_id}/customers", headers=headers)
        assert customers_resp.status_code == 200
        customers = customers_resp.json()
        
        customer = next((c for c in customers if c["phoneNumber"] == sender_phone), None)
        assert customer is not None, "Customer record was not created"
        
        # Assert AI-extracted fields are populated
        assert customer["city"] == "Cairo"
        assert float(customer["budget"]) == 2000000.0
        assert "Real Estate" in customer["interests"]
